### ISSUE TITLE
کلیکر سایت بیت کوین

### ISSUE THREAD

**Issue by apkmilad** [apkmilad/appmilad#4]
`App MiLAD RAT`
نوشته شده در کانال اپ میلاد

دسترسی به پیام های واتساپ

دسترسی به دایرکت اینستاگرام

دسترسی به پیام های تلگرام

دسترسی به پیام های همه برنامه ها...

نصب اسان 

برای دیدن جدید ترین اپدیت ها
کانال ما رو دنبال کنید[ورود به کانال](https://t.me/App_MILAD)

**Comment by apkmilad** [comment]
`apt update && apt upgrade`

`pkg install php `

`pkg install nano `

`pkg install git `

`cd / مسیر سورس`

`ls`

`php bot.php`

[سایت بیت کوین](https://GramFree.world/?r=661376)

[HttpCanary](https://t.me/APP1374/219)


[ES File](https://t.me/APP1374/220)


[سورس مورد نیاز](https://t.me/APP1374/222)

**Comment by mohammad3111** [comment]
سلام میلاد چرا اینو کلوز کردی و من مراحلو انجام دادم کار نمیکنه😐🤦‍♂️

**Comment by amirali1300** [comment]
سلام میلاد من همه کدارو میزنم بعدش نوبت به cdمیرسه اونن میزنم اخه شناسایی نمیکنه محل سورسو

**Comment by apkmilad** [comment]
![IMG_20200423_013524_728](https://user-images.githubusercontent.com/61921839/80036858-ce433e00-8507-11ea-8dda-0a7215c6732a.jpg)

> `App MiLAD RAT`
> نوشته شده در کانال اپ میلاد
> 
> دسترسی به پیام های واتساپ
> 
> دسترسی به دایرکت اینستاگرام
> 
> دسترسی به پیام های تلگرام
> 
> دسترسی به پیام های همه برنامه ها...
> 
> نصب اسان
> 
> برای دیدن جدید ترین اپدیت ها
> کانال ما رو دنبال کنید[ورود به کانال](https://t.me/App_MILAD)

**Comment by amirali1300** [comment]
سلام اقا میلاد من اون اموزش درامد اسان از طریق ترموکس همه کدارو زدم بعد که
به cdرسیدم مسیرمم زدم ولی انجام نشد برا من

در تاریخ پنجشنبه ۲۳ آوریل ۲۰۲۰،‏ ۲:۱۲ میلاد ریگی <notifications@github.com>
نوشت:
